MODEL:
  META_ARCHITECTURE: "TensorMask"
  MASK_ON: True
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[44, 60], [88, 120], [176, 240], [352, 480], [704, 960], [1408, 1920]]
    ASPECT_RATIOS: [[1.0]]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    FUSE_TYPE: "avg"
  TENSOR_MASK:
    ALIGNED_ON: True
    BIPYRAMID_ON: True
    NUM_CLASSES: 7
    SCORE_THRESH_TEST: 0.5
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/TensorMask/tensormask_R_50_FPN_6x/153538791/model_final_e8df31.pkl"
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.001
  MAX_ITER: 20000
INPUT:  # Limits for Tesla P100 with 16 GB VRAM
  MAX_SIZE_TEST: 1600
  MIN_SIZE_TEST: 1300
  MAX_SIZE_TRAIN: 1600
  MIN_SIZE_TRAIN: (1300,)
DATALOADER:
  NUM_WORKERS: 1
TEST:
  DETECTIONS_PER_IMAGE: 400
  EVAL_PERIOD: 500
VERSION: 2